title: RRAP-IS M&DS user documentation
description: User documentation for use of the RRAP-IS M&DS system 
# remote_theme: just-the-docs/just-the-docs
remote_theme: pdmosses/just-the-docs@rec-nav-2
logo: "/assets/images/iconRestoration.png"
search_enabled: true
heading_anchors: true
last_edit_timestamp: true
markdown: kramdown
aux_links:
  "RRAP-IS M&DS":
    - "https://www.rrap-is.com/"
  "RRAP":
    - "https://gbrrestoration.org/"

exclude:
  - development.md
