theme: "just-the-docs"
# remote_theme: pdmosses/just-the-docs@rec-nav-2
logo: "/assets/images/iconRestoration.png"
search_enabled: true
toc: false
heading_anchors: true
last_edit_timestamp: true
markdown: kramdown

exclude:
  - development.md