remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/iconRestoration.png"
search_enabled: true
heading_anchors: true
last_edit_timestamp: true
ga_tracking: G-XXXXXXX
footer_content: "<div><h3>Acknowledgement of Country</h3></div>
                <div>The Reef Restoration and Adaptation Program respects and recognises all Traditional Owners of the Great Barrier Reef as First Nations Peoples holding the hopes, dreams, traditions and cultures of the Reef.</div>
                <div>© Reef Restoration and Adaptation Program. All rights reserved. <a href="https://gbrrestoration.org/terms-and-conditions/">Terms &amp; Conditions </a><a href="https://gbrrestoration.org/privacy-policy/">Privacy Policy</a></div>"